web:
  image: hugh/myflask01
  volumes: 
    - /home/hugh/myshare/projects/vf_Ireland_2017/swgw_afg17ga:/data  
    # - /home/hugh/Downloads/data/swgw_afg17ga:/data
  ports:
    - "80:80"
  #command: 
